/**
 * Role Evolution model — the HR-facing artefact.
 *
 * The column that does not exist in any HR system today is the last one:
 * which developmental repetitions disappeared when the task was automated.
 * SYNTHETIC, illustrative of a BFSI GCC credit analyst role.
 */

export type TaskStatus = 'automated' | 'accelerated' | 'human-judgement' | 'emerging';

export interface RoleTask {
  task: string;
  before: string;
  now: string;
  status: TaskStatus;
  /** What the junior used to learn by doing this. */
  repsLost: string | null;
  /** What capability the new version of the role demands instead. */
  nowRequires: string | null;
}

export const ROLE_TASKS: RoleTask[] = [
  {
    task: 'Spreading financial statements',
    before: '3–4 hours per borrower, manually, from PDFs',
    now: 'Automated end to end in under a minute',
    status: 'automated',
    repsLost:
      'Line-by-line contact with the statements — where you learned which numbers move and which never do.',
    nowRequires: 'Ability to detect when an automated spread has mis-mapped a line item.',
  },
  {
    task: 'Drafting the credit memo',
    before: 'First draft written by the analyst, marked up by the VP',
    now: 'First draft generated by the assistant; analyst reviews',
    status: 'automated',
    repsLost:
      'The single richest learning loop in the role: your draft, a senior\'s markup, and the visible reasoning in between.',
    nowRequires: 'Evaluative judgement over a fluent draft you did not write.',
  },
  {
    task: 'Covenant computation',
    before: 'Built by hand in the credit model',
    now: 'Computed automatically and presented as a result',
    status: 'automated',
    repsLost:
      'Building the ratio yourself — which is how you learned what it is sensitive to.',
    nowRequires: 'Recomputation discipline and knowing the contractual definition.',
  },
  {
    task: 'Peer / comparable selection',
    before: 'Analyst researched and argued the peer set',
    now: 'Proposed automatically from sector codes',
    status: 'accelerated',
    repsLost: 'Arguing a comparison and having it challenged.',
    nowRequires: 'Checking that the sector template applies to this business model at all.',
  },
  {
    task: 'Document summarisation / data room review',
    before: 'Analyst read the full data room',
    now: 'Summarised on request',
    status: 'accelerated',
    repsLost: 'Incidental discovery — finding the affiliate schedule because you read everything.',
    nowRequires: 'Targeted evidence-seeking against specific assertions.',
  },
  {
    task: 'Materiality judgement',
    before: 'Learned implicitly over 18–24 months of markups',
    now: 'Required from month one',
    status: 'human-judgement',
    repsLost: null,
    nowRequires: 'Scrutiny allocation — the core capability SkillForge practises.',
  },
  {
    task: 'Exception handling and escalation',
    before: 'Encountered a few times a year, learned from the VP',
    now: 'Same rarity, but now the analyst is the first and often only human reviewer',
    status: 'human-judgement',
    repsLost: null,
    nowRequires: 'Deliberate exposure to exceptions that real work supplies too rarely.',
  },
  {
    task: 'Verifying AI output against source',
    before: 'Did not exist',
    now: 'Core daily activity',
    status: 'emerging',
    repsLost: null,
    nowRequires: 'Provenance discipline: a source for every specific claim.',
  },
  {
    task: 'Knowing when not to overrule the model',
    before: 'Did not exist',
    now: 'Distinguishes value-adding reviewers from value-destroying ones',
    status: 'emerging',
    repsLost: null,
    nowRequires: 'Evidence-based restraint.',
  },
];

export const STATUS_LABEL: Record<TaskStatus, string> = {
  automated: 'Automated',
  accelerated: 'Accelerated',
  'human-judgement': 'Human judgement',
  emerging: 'Emerging',
};
